<?php

namespace Accordous\AsaasClient\Enums;

class WebhookEvents extends Enums
{
    public const PAYMENT_CREATED = 'PAYMENT_CREATED';
    public const PAYMENT_UPDATED = 'PAYMENT_UPDATED';
    public const PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';
    public const PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';
    public const PAYMENT_OVERDUE = 'PAYMENT_OVERDUE';
    public const PAYMENT_DELETED = 'PAYMENT_DELETED';
    public const PAYMENT_RESTORED = 'PAYMENT_RESTORED';
    public const PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';
    public const PAYMENT_RECEIVED_IN_CASH_UNDONE = 'PAYMENT_RECEIVED_IN_CASH_UNDONE';
    public const PAYMENT_CHARGEBACK_REQUESTED = 'PAYMENT_CHARGEBACK_REQUESTED';
    public const PAYMENT_CHARGEBACK_DISPUTE = 'PAYMENT_CHARGEBACK_DISPUTE';
    public const PAYMENT_AWAITING_CHARGEBACK_REVERSAL = 'PAYMENT_AWAITING_CHARGEBACK_REVERSAL';
    public const PAYMENT_DUNNING_RECEIVED = 'PAYMENT_DUNNING_RECEIVED';
    public const PAYMENT_DUNNING_REQUESTED = 'PAYMENT_DUNNING_REQUESTED';
}
